### ISSUE TITLE
Relations always show as hidden

### ISSUE THREAD

**Issue by DaGwann** [eXaminator/kanka-foundry#101]
When I create and link new characters, or update already linked characters, the relations are set to hidden no matter what permissions I give them.

Deleting the journal entry from Foundry and linking it again to Kanka doesn't fix the issue. This happens even to old entries that haven't been updated in a good while and still have relations with the permission I set. When I update them individually, the relations are automatically hidden, as if the permissions were set to admin in Kanka. The only way to fix this is changing permissions in Foundry from Observer to Owner. As far as I've tested, this issue doesn't happen with any other aspect of a Kanka entry.

**Comment by eXaminator** [comment]
Hey, thanks for this. I just checked it and it seems to be a bug in Kanka itself. I just posted it on their Discord and we'll see where it goes from there. I'll keep this issue open for now until it's fixed.

**Comment by eXaminator** [comment]
I didn't follow up on this, but right now it seems that this bug is fixed and I see private relations as well as public relations (the latter without the "private" styling). Does this now work for you too?

**Comment by eXaminator** [comment]
I will close the issue now. Should you still see this error feel free to comment and I might open it up again.
