### ISSUE TITLE
foundry hud weblate

### ISSUE THREAD

**Issue by eunaumtenhoid** [eXaminator/kanka-foundry#104]
hi, is it possible to add your mods to foundry hud weblate for us to translate or update the translation faster? https://weblate.foundryvtt-hub.com/

**Comment by eXaminator** [comment]
@eunaumtenhoid The project is now on weblate and can be translated. If I'm not mistaken you also created the brasilian language, but with no translations yet. So I'll keep the PR open for now until there is some text in there. Hopefully everything works now :)
