### ISSUE TITLE
[Documentation] Can you explain how to activate/use the developing on the readme ?

### ISSUE THREAD

**Issue by p4535992** [eXaminator/kanka-foundry#117]
Forgive me I must be really stupid I must be doing something wrong on my side when I try to activate the developing with vite.

Could you put a few lines explaining the steps I should do to hot reloading te code ?

**Comment by eXaminator** [comment]
Hey, sorry, I was busy recently. Have you figured it out or given up? O probably should at some info on how to get this module running for development. 😅

**Comment by p4535992** [comment]
No sorry me, I had tried some time ago to do the integration with MJE, but I stopped almost immediately to follow other modules.

If you can add some information on how  debug the project, it would be helpful if I want to come back to it.

**Comment by eXaminator** [comment]
I have added some documentation for this. Hopefully that is helpful.
