### ISSUE TITLE
Kanka 2.0 broke something.

### ISSUE THREAD

**Issue by Nedrapter** [eXaminator/kanka-foundry#119]
Kanka has its update today. Something seems to have broken. After making a new token, it is not detecting any campaigns in my Foundry.
![image](https://github.com/eXaminator/kanka-foundry/assets/74311190/c8bfecee-3b6d-416b-948e-60234991509e)
Not sure if relevant but I want to mention: my campaign from boosted changed to premium (the old system and the new for subscribers) and instead of a random number it now has a vanity url.

**Comment by eXaminator** [comment]
Hi @Nedrapter ,

have you updated to the latest version? I have released two new versions of the module that fixed bugs regarding the Kanka 2.0 integration just about 1 or 2 hours before you posted.

If this error still persists: Could you please check the devtools console on your browser or Foundry client (usually F12 on Windows or Cmd +  alt + i on mac, then make sure you're on the "console" tab) for any (red) errors that might be related to Kanka? You might want to reload Foundry (F5 or Cmd + R) to make sure you see any errors coming up when initializing the module. It would be very helpful if you could post copies or screenshots of those errors here. 

Thanks!

**Comment by Nedrapter** [comment]
I'm on Kanka 3.1.11
I see the following error related to Kanka:
![image](https://github.com/eXaminator/kanka-foundry/assets/74311190/0b0e07a5-3938-4a96-bee1-5c1913aa711a)
I have reloaded and relaunched my worlds.

**Comment by eXaminator** [comment]
Error 401 means you are not authorized to access that URL (in this case the list of campaigns). Could you please generate a new access token in Kanka and try that? Maybe your token has expired. If that still doesn't work I'll investigate a bit more in regards to vanity URLs, though I'm not sure why that would result in a 401 error 🤔

**Comment by Nedrapter** [comment]
> Error 401 means you are not authorized to access that URL (in this case the list of campaigns). Could you please generate a new access token in Kanka and try that? Maybe your token has expired. If that still doesn't work I'll investigate a bit more in regards to vanity URLs, though I'm not sure why that would result in a 401 error 🤔

Made a new one just now. Same result.

**Comment by Nedrapter** [comment]
![image](https://github.com/eXaminator/kanka-foundry/assets/74311190/871dc5f8-432f-486a-a9f9-c1261d602f2f)
This also was in the console now

**Comment by eXaminator** [comment]
Thanks for all the info. I'll look into this soon and will try to fix the issues.

**Comment by Nedrapter** [comment]
Made a 4th new token but from a different browser. It seemed to work passed the step I had issues with. Then it wasn't saving my campaign choice. Then after a reload of the world, it worked. Not sure if copying it from Opera was the issue (then used Firefox), or the 4th new token fixed it...
Thanks for the assistance though!

**Comment by icewolf08** [comment]
I am also getting a similar error and not able to get the plugin to connect. I have tried three new API tokens including creating one in a different browser. I am getting the following errors: 
![image](https://github.com/eXaminator/kanka-foundry/assets/68305052/6de07616-672e-4baf-9aa4-4d57d70cc58d)
![image](https://github.com/eXaminator/kanka-foundry/assets/68305052/1a0ce6e8-8e32-4d29-bcc7-2e6a9d481c2b)
It looks like the plugin is trying to call an incorrect url: `https://api.kanka.io/api/1.0/campaigns` but I think it should be: `https://api.kanka.io/1.0/campaigns` based on all the info and screenshots in previous posts.

**Comment by eXaminator** [comment]
Hi @icewolf08 ,

yep, the URL in that screenshot is wrong. Please make sure you have set "api.kanka.io" as base URL in the settings and have also updated to the latest version of the module. That should hopefully fix it for you.

**Comment by icewolf08** [comment]
@eXaminator it seems that it was something stuck in my browser cache. Killing chrome and re-launching allowed it to work correctly.

**Comment by eXaminator** [comment]
Thanks for letting me know. I will close this issue now. Let me know if you have any more errors and I'll reopen it.
