### ISSUE TITLE
Linked entities opens directly in Kanka

### ISSUE THREAD

**Issue by jero-rodriguez** [eXaminator/kanka-foundry#120]
Hi, 

I have migrated to kanka-foundry 3.1.11 and noted that with this url in settings **https://api.kanka.io**

![image](https://github.com/eXaminator/kanka-foundry/assets/8132753/f90dc98f-7c45-4018-b6bd-d24563c13909)

It shows all the links directly in kanka but no errors in console.

In the other hand, if I change the url to this: **https://kanka.io**

![image](https://github.com/eXaminator/kanka-foundry/assets/8132753/ab31ebff-3572-40f7-9f36-ade013691a43)

The links in the journal shows correctly inside foundry vtt and in the console I can see this error

![image](https://github.com/eXaminator/kanka-foundry/assets/8132753/bf735975-7c42-455a-94f7-49e54e4d65a7)

Is this bug on the module or I'm doing something wrong?

Thanks and regards!

**Comment by eXaminator** [comment]
Hi,

thanks for the info. This looks like a bug and I have an idea why it might happen. I'll try to investigate this further soon and hopefully I can release a fix soon after.
