### ISSUE TITLE
Players cannot close Kanka journal

### ISSUE THREAD

**Issue by Steauxback** [eXaminator/kanka-foundry#130]
Players can open Kanka journal if allowed but cannot close the journal screen. This only affect journal created by Kanka-Foundry, journal created directly from FoundryVTT can be closed without issues.
Tested on a world with only Kanka-foundry as a module.
FoundryVTT 11 build 315
Kanka-foundry 4.0.8

**Comment by eXaminator** [comment]
Should be fixed in the new version which will be released in a few minutes.
