### ISSUE TITLE
Hidden information visible to players

### ISSUE THREAD

**Issue by FenrisHakaari** [eXaminator/kanka-foundry#136]
I cannot find any information about player visibility but I am assuming that items with permission set to GM/Admin only are not visible to players after importing to Foundry. In the screenshot below Teara and Anadea are not visible to players (I guess the crossed eye icon suggests that).  When I check while logged in as a player it works perfectly fine

**GM view:**
![image](https://github.com/eXaminator/kanka-foundry/assets/115780371/e3b9e162-aa32-40a2-8ddc-9d2d22fc38de)
**Player view:**
![image](https://github.com/eXaminator/kanka-foundry/assets/115780371/39ed1427-9e32-446a-a1a0-ff9ae46fd751)

But then I noticed in the Members section all information is visible to players.

**GM view:**
![image](https://github.com/eXaminator/kanka-foundry/assets/115780371/697717bb-d081-4c6c-bb10-6f1333a12194)
**Player view:**
![image](https://github.com/eXaminator/kanka-foundry/assets/115780371/a18902fa-2731-453c-809b-433cadae9a28)

Is this a bug? Intentional? Software limitation? Some information on how it works would be great.

**Comment by develroo** [comment]
Did you check the box at the bottom of the form under configuration settings? 

![Screenshot from 2024-07-14 21-47-48](https://github.com/user-attachments/assets/d3dc4a8f-98e7-4c6e-8f19-869f35cbe8f7)

**Comment by FenrisHakaari** [comment]
I have it to set permissions on every update. Should I change it?
<img width="797" alt="image" src="https://github.com/user-attachments/assets/991de1e6-2ba5-470a-8e56-53c4aad95ee8">

**Comment by eXaminator** [comment]
Hey, I've had a lot of stuff on my plate recently. I'll see if I can find some time to look into it soon and see if I can reproduce this!

**Comment by FenrisHakaari** [comment]
No rush, thanks for help
