### ISSUE TITLE
Location's player permissions not working correctly

### ISSUE THREAD

**Issue by FenrisHakaari** [eXaminator/kanka-foundry#139]
Individual page permissions in the location journal are not set up correctly. A page called "Droga" should be hidden for players and it is not, all pages are visible to players. Looking at the previous journals it did work correctly in the past, only recently changed. And yes, I have set this up to update permissions on each update. I've tried to change visibility of whole journal and it is picking it up correctly, only individual "sections" aren't working correctly. 

![image](https://github.com/user-attachments/assets/07edb63c-962c-4cd4-a812-7a1c3a7ecdc9)

![image](https://github.com/user-attachments/assets/8093c853-52b5-432b-a58c-f6473fbd42e6)

**Comment by OWL-Fashioned** [comment]
+1
It not only seems to be an issue for locations. I have recognized the same problem, when hiding posts of objects. :-(
