### ISSUE TITLE
[BUG] Overview entry missing

### ISSUE THREAD

**Issue by TheAsel** [eXaminator/kanka-foundry#141]
The overview entry description is missing if an entity doesn't have a post inside. For example, a location shows its name, type, parent and image but no entry.

**Comment by TheAsel** [comment]
I think the problem is on line 235 of PageFactory. It returns an empty array if there are no posts, skipping the overview entry. I tried commenting out the line and after refreshing an entity it appears to work, but this quick fix probably breaks something else.

**Comment by Metacomet10** [comment]
Also experiencing this

**Comment by eXaminator** [comment]
Should be fixed in the new release. Though you'll have to reimport entries with the missing page.
