### ISSUE TITLE
[BUG] Missing Loader for type Calendar

### ISSUE THREAD

**Issue by Metacomet10** [eXaminator/kanka-foundry#142]
Hello,
When clicking the Link All button for the campaign the following error occurs:
```
Kanka-foundry  |  Error: Missing loader for type calendar
    at createEntity (syncEntities.ts:23:24)
    at createEntities (syncEntities.ts:53:19)
    at HTMLButtonElement.<anonymous> (KankaBrowserApplication.ts:273:35)

logError  @  logger.ts:8
(anonymous)  @  KankaBrowserApplication.ts:326
await in (anonymous) (async)
dispatch  @  jquery.min.js:2
y.handle  @  jquery.min.js:2
```
The error only pops up when syncing entities from a campaign that has a calendar created in Kanka.
The error does not pop up if clicking the Link All button for each individual category, even the Events category on a campaign that *does* have a calendar.

If there are Event entities in the campaign that are trying to link/update it halts the linking process for categories listed below Events in the list.

I tried activating the Simple Calendar module to see if that would affect it and nothing changed. I didn't think they were connected but worth a shot lol

Please let me know if you need any additional info from me or screenshots

------

Verified error occurs in brand new worlds using dnd5e 1.6.3 and also Stars Without Number 1.1.0
No other modules active.
Foundry version 11.315
Kanka module version 4.1.3

**Comment by eXaminator** [comment]
This was an easy fix, but maybe not in the way you would like. This module doesn't really have support for calendars yet. Only in the sense that it gets some information of them for events on other entities, but not as a "first class citizen". 

I now fixed the error handling  – the error will still be there in the console (though now as a warning), but it shouldn't stop the execution for the other entity types.
