### ISSUE TITLE
Custom attributes are empty

### ISSUE THREAD

**Issue by gluonlive** [eXaminator/kanka-foundry#144]
Custom attributes seem to be empty.

![image](https://github.com/user-attachments/assets/1fe03650-2396-4e33-a007-7f503c4eb450)

**Comment by Varkal** [comment]
Same issue here !

**Comment by eXaminator** [comment]
There was a change with attribute types in Kanka it seems. I changed the code and it should also be at least somewhat more resilient to similar changes in the future.
