### ISSUE TITLE
Entity links do not include language, give 404

### ISSUE THREAD

**Issue by OfficerHalf** [eXaminator/kanka-foundry#27]
Example to repro:

1. Create Quest with link to a location in its entry
2. Link quest in Foundry
3. In Foundry journal entry, click link to location
4. End up on Kanka's 404 page

Problem is it seems to be missing the `/en-US/` part of the link and it doesn't end up in the correct place. I assume that's something injected on Kanka's side. If it matters, I used a [location:xxx] style link, not an @ link.

Similar issue on the import UI for links to Races/Quests/etc. Clicking on one of the titles attempts to open Kanka with a language of `null`.

**Comment by eXaminator** [comment]
That is strange. There should be a fallback in place that uses the language in your profile if available, or falls back on the campaign locale... or, if that's missing too, it should fall back to english.

I'll take another look this weekend though with your specific steps and see what happens. Might be something I broke with one of the last updates :)

**Comment by eXaminator** [comment]
@OfficerHalf Please check if the update fixes your issue. I was mistaken regarding the profile language, so I know added that in too. Hopefully it works for you!
