### ISSUE TITLE
Optional Removal of "[KANKA]" from Journal entries

### ISSUE THREAD

**Issue by Unikatze** [eXaminator/kanka-foundry#38]
It's a great way to see which entries came from Kanka and which ones were made directly in Foundry. However, when an entire campaign is made in Kanka then it's kind of redundant. 
Maybe have an option in settings to remove this, make it smaller (like [K]) or an icon (I don't think Foundry Allows this) to make it less intrusive would be nice.

**Comment by eXaminator** [comment]
Hi @Unikatze, thanks for your Feedback.

You can actually rename folders (and change any other options presented by Foundry like color etc.) after they were created by the module to whatever you like and it will keep using that folder for the specific type of entries. So if you rename "[KANKA] Characters" to "Awesome Characters" it will keep importing all future characters into that folder.

Please let me know if that's enough for your use case. Maybe I should add a paragraph to the readme regarding this. :)

**Comment by eXaminator** [comment]
I just updated the readme to add this info. Please let me know if more is needed to in this regard.
