### ISSUE TITLE
Organizations to Import Members

### ISSUE THREAD

**Issue by chekmx** [eXaminator/kanka-foundry#41]
Loving this plugin.  Thanks for the works so far.  I would find it really helpful if you could optionally import a list of members to an organization in the same way  that Characters can import a list of organizations to which the belong.

**Comment by eXaminator** [comment]
Thank's for this suggestion. This is a good idea and there will probably be an update to the Kanka API soon that will simplify this, so it's likely I will implement this.

Though I have been thinking about some bigger rewrites in parts of the module (which would enable further features in the future), so this might be postponed till after that update (or maybe it will be implemented at the same time).

**Comment by eXaminator** [comment]
You now get the list of members for organizations with Version 2.0.0.

**Comment by chekmx** [comment]
Thanks this is great.  As is the whole release.  Really nice.
