### ISSUE TITLE
Failed to fetch campaign, sync with Kanka, CORS error.

### ISSUE THREAD

**Issue by huxoll** [eXaminator/kanka-foundry#43]
Suddenly this evening, I get an error trying to sync Foundry with Kanka.

Error:
Access to fetch at 'https://kanka.io/api/1.0/campaigns/{my-campaign}?related=1' from origin 'http://localhost:30000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I regenerated an API key, but I'm getting the same response.

**Comment by eXaminator** [comment]
Hi huxoll.

Kanka has been experiencing DDoS attacks in the last couple of days, which causes Cloudflare (their hoster) to switch into an Anti-DDoS mode. Sadly, this breaks the API. I have been in contact with the Kanka team though, in hopes that this can be somehow resolved on their end.

If nothing else we just need to wait and hope for it to work again after a while and for the DDoS attacks to stop soon. 😞

**Comment by eXaminator** [comment]
Here's the official announcement from Kankas Discord chat:

> We've been getting hit by ddos attacks all day, resulting in the app acting weirdly and some data loss. We're activating the ddos protection again, which sadly kills the API part of Kanka until the attacks stop

**Comment by huxoll** [comment]
It seems the DDOS storm is over, I can sync again.  Thanks for looking into it.
