### ISSUE TITLE
Inconsistent fetching causes issues with ancestors attribute

### ISSUE THREAD

**Issue by TvanBronswijk** [eXaminator/kanka-foundry#45]
In `KankaApi.ts`, single entities are inconsistently fetched from the API. Currently, when trying to fetch a single race from Kanka, I'm getting the error `n.ancestors is undefined`. When I have multiple outdated races, it seems to work fine. Other entities also work fine with single results. I believe it's the inconsistent matter of fetching that's the issue.

**Comment by eXaminator** [comment]
Thank's for this! I'll publish a fix for this soon!
