### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by Sandman2055** [eXaminator/kanka-foundry#51]
I keep getting the migration dialog box on starting my world telling me I have 1 journal entry that needs updating  https://i.imgur.com/5oeJ45B.png.  I only have a single campaign in Kanka  https://i.imgur.com/vXbNSdb.png  Updating and overwriting my entries gives an error message of not finding entries to migrate.  https://i.imgur.com/HMXtyce.png

**Comment by eXaminator** [comment]
Hi, another reason for this that I can think of could be, that you have an entry in foundry that was deleted in Kanka.

Ist that possible in your case?

**Comment by Sandman2055** [comment]
Possibly.  How could I find out which it is?  I assume if I can find it in foundry and delete it, the pop up will go away?

**Comment by eXaminator** [comment]
I'm almost done with version 2.1.0 of the module and plan to hopefully release it sometime tonight (CEST). I will try and improve the migration dialog before I release the new version, so that it lists all entries that need migration. This should help identify the culprit.

**Comment by eXaminator** [comment]
@Sandman2055 I just released version 2.1.0. Please check it out, you should now get a list of journal entries that need migration and should be able to find the culprit. Please let me know if you can now resolve the issue!

**Comment by Sandman2055** [comment]
It worked perfectly!  So handy.  It listed the offending entry and I was able to delete it - didn't really need it anyhow.  Now there's no dialogue.  Thanks!
