### ISSUE TITLE
Race ancestors are displayed twice

### ISSUE THREAD

**Issue by TvanBronswijk** [eXaminator/kanka-foundry#53]
Race ancestors are found using the `race_id` property. The sheet template for races displays both `race_id` and `ancestors`. Because of that, ancestors are effectively displayed twice. Only showing `ancestors` should be enough.

https://github.com/eXaminator/kanka-foundry/blob/e20a229332a7ba51d7e44b3c8d92b85c82b512db/src/KankaJournal/sheets/race.partial.hbs#L4-L5

**Comment by eXaminator** [comment]
Good find, thanks! I will fix that as soon as I can. :)

**Comment by eXaminator** [comment]
I just fixed this in 2.1.1
