### ISSUE TITLE
Notes are no longer pinned

### ISSUE THREAD

**Issue by jonepatr** [eXaminator/kanka-foundry#54]
Seems like kanka made some changes and are not allowing to pin notes anymore. Could it be possible to have an option in the settings to always pin all notes, since it's really nice to have them on the first page of the journal entry.

**Comment by eXaminator** [comment]
Thanks for pointing this out. I'll have to consider how I want this module to adapt to the recent Kanka update. I generally want to keep the module kind of close to how Kanka handles thinks, so having an option like this (probably enabled by default) makes sense.

I'll also have to consider if I want to mirror the distinction between "Story" and "Profile". 🤔 Maybe as an option but with a setting that moves the Profile to the Story tab (which would basically be like it is right now).

I'll see what I can do over the weekend.

**Comment by eXaminator** [comment]
This is fixed in 2.2.0 by always showing notes on the first tab just like Kanka does now.
