### ISSUE TITLE
Bug - When the module is active I am no longer able to edit the text of the Foundry journals on Foundry 0.8.8

### ISSUE THREAD

**Issue by p4535992** [eXaminator/kanka-foundry#56]
**Environment Details**

Foundry VTT Version: 0.8.8

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.6

Modules Enabled?: No

Module version: 2.2.0

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

When the module is active I am no longer able to edit the text of the Foundry journals

Without the module.

![img1](https://i.imgur.com/fVpJici.png)

With the module.

![img2](https://i.imgur.com/dl0ufFP.png)

**Comment by eXaminator** [comment]
Hi @p4535992 ,

thank you for the report! I totally missed that. Not only did the editing not work, but the styles were also broken (which was my fault!).

This should no be fixed with the latest 2.2.1 update!
