### ISSUE TITLE
Issue on the manifest json can't install/update anymore from Foundry Package Manager

### ISSUE THREAD

**Issue by p4535992** [eXaminator/kanka-foundry#59]
Error: The request to https://github.com/eXaminator/kanka-foundry/releases/download/__VERSION__/module.json did not provide a valid manifest file.

**Comment by eXaminator** [comment]
Hi, thanks for the issue. I removed the problematic release. It seems my automated release process is still having some issues. Thanks for bringing it to my attention, I hope I can keep this from happening again!
