### ISSUE TITLE
Add visual indicator for complete quests in the sidebar

### ISSUE THREAD

**Issue by odyseja2011** [eXaminator/kanka-foundry#61]
If it is possible please add some way of differentiating completed quests from incomplete ones in the sidebar - like and icon or color. Ones there is tone of them it gets hard for players to keep track :)

**Comment by eXaminator** [comment]
I like the general idea.

I'll just leave this idea here for now: Maybe the simplest way could be to just add some sort of icon (or unicode symbol) to each quest name when importing.
