### ISSUE TITLE
Update permissions when updating changed entries

### ISSUE THREAD

**Issue by brockhaus** [eXaminator/kanka-foundry#69]
First of all: Thanks for that plugin! I was thinking to do something similar, but your's seem to be very helplfull already! :)

My suggestion: The plugin can update all content when changed in Kanka. When adding new entries, it will distribute permissions as expelcted. Very nice! 

But when updating entities it won't change permissions. This might be by feature in order to not override permissions already set manually. Perhaps have a configuration or a flag on the main Kanka dialogue?

**Comment by eXaminator** [comment]
Hi, thanks for your feedback!

I'll think about it, might be easily done by extending the configuration a bit and probably makes sense to add this to updates also.
