### ISSUE TITLE
BUG - The Standard Journal Image not work anymore with 2.3.7

### ISSUE THREAD

**Issue by p4535992** [eXaminator/kanka-foundry#71]
**Environment Details**

Foundry VTT Version: 0.8.8

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.4.1

Modules Enabled?: Yes (if you need i can give you the full list)

Module version: 2.3.7

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

When i click on the image panel of the standard journal of Foundry now i see the "embedded" version of the image with no url at the bottom.

![img](https://i.imgur.com/UqlIuGC.png)

~~This error was not present this Wednesday when I did the session, so it must be something inserted after version 2.3.5 / 2.3.6, or maybe some conflict with the update of the module [_document-sheet-registrar](https://github.com/League-of-Foundry-Developers/document-sheet-registrar/releases/latest/download/module.json)~~

**Confirmed with some test is something done between 2.3.6. and 2.3.7 version (tested with last version of [_document-sheet-registrar](https://github.com/League-of-Foundry-Developers/document-sheet-registrar/releases/latest/download/module.json) 0.5.0 )**.

**Comment by eXaminator** [comment]
Thanks for this issue. Let this be a lesson in doing hasty changes without properly testing them... 🤦 Should be fixed in the new release coming up in a few minutes.
