### ISSUE TITLE
Maybe issue or user error

### ISSUE THREAD

**Issue by sm-thirdman** [eXaminator/kanka-foundry#72]
Hi,

I have a character in Kanka with Attributes.

<img width="339" alt="Screenshot 2021-08-08 at 10 18 55" src="https://user-images.githubusercontent.com/82657085/128627236-24f8fd97-9f85-43b5-ae3f-6371fbd5d00a.png">

When I link/update tis character I get the following under attributes:

<img width="671" alt="Screenshot 2021-08-08 at 10 19 05" src="https://user-images.githubusercontent.com/82657085/128627255-b1485f60-5c11-46c3-91c4-ef266aff5cf6.png">

It seems to be picking up the 'Section' titles in Kanka, but not the attributes with values.

Sam.

**Comment by eXaminator** [comment]
Hey there,

that is indeed strange. So let me ask you a couple of questions, because your screenshots are missing a couple of key parts that might be helpful here 😁 

1. What are the settings for these attributes? Are they private or public? Have you starred them?
2. Are they missing for you as GM in that world or are just the players not seeing them?

If they are missing for your GM user, I'd ask you to export the journal entry from Foundry and post the file here. That way I can take a look at the underlying data and see if I can find out why theses attributes are missing.

**Comment by sm-thirdman** [comment]
Hi,

1. These attributes are set to public and not starred.


![Screenshot 2021-08-08 at 10 49 26](https://user-images.githubusercontent.com/82657085/128628306-2fac36d2-0b2e-4502-9c7a-c751b5f0b282.png)

2. They are missing for me as the GM as well as players

JSON attached.

Sam.

[fvtt-JournalEntry-glarren-everway.json.zip](https://github.com/eXaminator/kanka-foundry/files/6950517/fvtt-JournalEntry-glarren-everway.json.zip)

**Comment by eXaminator** [comment]
Thanks, I was able to reproduce and fix this issue.

That being said, the ordering of the attributes is broken. I'm currently trying to check with the Kanka team what's up with that and will hopefully release an update once I have verified what the correct behavior is supposed to be (probably sometime today).

**Comment by sm-thirdman** [comment]
Many thanks!

Sam.

**Comment by eXaminator** [comment]
This was closes automatically, but I'll reopen it because there is still the issue with the sorting that is kind of related to this (and because that would probably be the next issue you would open for that same character 😛).

**Comment by sm-thirdman** [comment]
I saw that you asked about this on the Kanka forum.

What is the issue?  Is there something I can do with Kanaka attributes (I don't have to have Sections) that would make this work?

Sam.

**Comment by eXaminator** [comment]
Not that I am aware of. I think the order of stuff gets scrambled if you use multiple attribute templates, but that is just a guess.

You could try changing the order of entries on your character, save it and then move it back. Maybe that fixes it (at least for the moved entries)? But I don't know if that's the case as I haven't tested that yet.

**Comment by eXaminator** [comment]
Ok, I was dumb and it was a simple mistake on my part. I'll release an update in a few minutes that should fix the sorting issue.
