### ISSUE TITLE
500 Errors preventing updates

### ISSUE THREAD

**Issue by snakch** [eXaminator/kanka-foundry#90]
Hi all,

While using the app, I'm suddenly getting 'An error occured while performing the requested action.' whenever I try to link or update an entry.

Looking at the console, I'm getting a 500 error. 
I've tried this on hosted and locally served servers, and for Forve 0.8.9 and v9. I also tried switching out my API access token to no avail. Note that this wasn't happening about a week ago, for me. 

It seems the response I get is

```
{"message":"Unauthenticated (missing the authorization token in the request headers, or the token is invalid).","documentation":"https:\/\/kanka.io\/en\/docs\/1.0\/setup#authentication"}
```

Any idea what's happening?

**Comment by eXaminator** [comment]
Hey @snakch,

I cannot reproduce this, so it doesn't seem to be a general error with Kanka or this module.

My best guess would be to create a new token, but you already did this...
So, let's see if we can gather some information about this and maybe we stumble upon something :)

1. Is the list of available campaigns properly loaded when going to the settings?
2. Do you have access to the campaign in Kanka and is it still available? (yes yes, I have to ask this, just to be sure ;))
3. Does this also happen with other campaigns?
4. Is the list of entities correctly loaded where you can update / link them? Or does this also fail?
5. Does this happen for all entity types / all entities of a type?

If we can break this down (to a specific campaign, entity type etc.), we can pass this on to the Kanka team to further investigate.

**Comment by snakch** [comment]
Thanks for the reply. Good questions! I only had one campaign so I quickly made a dummy one.

1. The list loads correctly
2. The campaign I care about is available
3. This issue does **not** appear for other campaigns - I'm able to load entities fine
4. The list of entities is correctly loaded
5. The issue seems to happen for all entity types

# 3 seems like a big hint - any idea what could be happening?

**Comment by eXaminator** [comment]
I agree, something seems to be strange with your campaign. Could you post the campaign ID? That way I could bring it to the Kanka team in discord and see if they can investigate the issue.

**Comment by snakch** [comment]
Thanks, it's 88793

**Comment by snakch** [comment]
Ok I've gotten in touch with them and they've fixed it already. Thanks for the assist!
