### ISSUE TITLE
[FEATURE] Allow connections to self-hosted Kanka instances

### ISSUE THREAD

**Issue by develroo** [eXaminator/kanka-foundry#95]
What is says in the title. I run a self-hosted Kanka for offline play and I would like to be able to import resources into my self-hosted Fvtt, again for offline play.

Can you make a config file or some config option that allows you to change the root url to a custom one?

The services could both be hosted on the same machine via docker, so mandatory SSL checks are not required, but should be optional. 

Thanks for your efforts. It is a great tool otherwise.

**Comment by eXaminator** [comment]
Hi @develroo,

I would love to add this feature. In fact, I just started implementing it.

That being said, I don't have a privately hosted Kanka environment to test if it actually works. Would it be possible for you to grant me temporary access to your environment to test this (ideally a new campaign with a few test entities and a custom user with the necessary token).

You can contact me on discord (eXaminator#0079) if you would be up for this :) (as you probably shouldn't share any details of your environment here).

**Comment by develroo** [comment]
> That being said, I don't have a privately hosted Kanka environment to test if it actually works.

Well, it can be set up relatively easy with docker. I followed [this guide.](https://github.com/owlchester/kanka/blob/develop/docs/running.md)

But I can always make you an account on my server. I'll try to contact you on Discord.
