### ISSUE TITLE
Module settings not available

### ISSUE THREAD

**Issue by Redund0** [eXaminator/kanka-foundry#97]
Kanka-foundry does not show up in module settings. I have both it and Lib doc installed. First install, have not used before.
Foundry Version 9 Build 280
Pathfinder 1 .81.3
![Capture](https://user-images.githubusercontent.com/112259739/187032514-e113c9ef-38e4-4c21-a7c5-d21a7a8b37fc.JPG)

**Comment by ronsolocup** [comment]
I am also having this issue. Additionally, the journal entries imported from Kanka are no longer able to be opened.

**Comment by eXaminator** [comment]
Version 2.11.1 should be released soon and should fix this issue. Please give it a try. Sorry for the inconvenience!
