### ISSUE TITLE
Show entity events

### ISSUE THREAD

**Issue by eXaminator** [eXaminator/kanka-foundry#99]
Events for entities are not yet imported and displayed. This should be changed.

- There should be a tab with all events for an entity.
- The "founded" or "birth" date event should be displayed on the main tab.

**Comment by develroo** [comment]
Perhaps being able to add calendars and adding them to Simple Calendars might be an easier compromise?

**Comment by eXaminator** [comment]
The tab with all "Reminders" has been there for a while now. I now also added the birthday and day of death to characters as well as the founded date for locations to the overview page.
